#!/bin/sh

echo "Enter y to add directories for the builder and server:"

read LINE

if [ $LINE = "y" ] 
then 
    echo "Copying directories.."
    cp -r ./.project/server ./.project/build ./.project/www ./
    cp ./.project/.gitignore ./
else
    echo "Not copying directories."
fi 


PROJECT_NAME=`basename $PWD`
echo $PROJECT_NAME
echo "Creating package.js and bower.js.."
cp ./.project/package.js ./
sed -i "s/projectname/$PROJECT_NAME/g" ./package.js
cp ./.project/bower.js ./
sed -i "s/projectname/$PROJECT_NAME/g" ./bower.js
cp ./.project/README.md ./
echo "Adding README.md.."
sed -i "s/projectname/$PROJECT_NAME/g" ./README.md
echo "Removing bower_components and node_modules directories.."
rm -rf bower_components
rm -rf node_modules
echo "Installing npm module fs-extra.."
npm install fs-extra
echo "Creating package.json and bower.json.."
node package.js
node bower.js
echo "Installing packages.."
npm install
bower install

chmod uga-x ./init
echo "//Empty source file" > src/$PROJECT_NAME.js
bin/docs

echoe "Removin git repo and creating new.."
rm -rf .git

git init
git add -A
git commit -m 'first commit'
echo "Remote added for michieljoris git user.."
git remote add origin "git@github.com:Michieljoris/$PROJECT_NAME"
echo "Done."

